name = "durable-rusty-limiter"
main = "build/index.js"
compatibility_date = "2026-07-05"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[vars]
COOLDOWN_IN_MS = "60000"
MAX_REQ_PER_SEC = "10"

[durable_objects]
bindings = [
  { name = "RUSTY_LIMITER", class_name = "RustyLimiter" } # the `class_name` uses the Rust struct identifier name
]

[[migrations]]
tag = "v1" 
new_sqlite_classes = ["RustyLimiter"] 
